heat_template_version: 2014-10-16

parameters:
  key_name:
    type: string
    description: keypair to enable SSH access to the instance.
    default: heat_key
  image:
    type: string
    description: ID of the image to use for the instance to be created.
    default: centos7-software-config-v3
  flavor:
    type: string
    description: Type of the instance to be created.
    default: m1.small
  count:
    type: number
    default: 1

resources:
  RGT:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: count}
      resource_def:
        type: OS::Nova::Server
        properties:
          name: rgt_server_%index%
          image: {get_param: image}
          key_name: {get_param: key_name}
          flavor: {get_param: flavor}

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: {get_attr: [RGT, attributes, addresses, private, 0, port]}

outputs:
  rgt_ports:
    value: {get_attr: [RGT, attributes, addresses, private, 0, port]}

  rgt_attr_show:
    value: {get_attr: [RGT, attributes, show]}

  rgt_net:
    value: {get_attr: [RGT, attributes, networks]}

  # (OK): 'attributes' with path
  rgt_id_dict_w_path:
    value: {get_attr: [RGT, attributes, show, id]}

  rgt_ip_dict_w_long_path:
    value: {get_attr: [RGT, attributes, first_address]}
