heat_template_version: 2014-10-16

parameters:
  image:
    type: string
  key_name:
    type: string
  flavor:
    type: string
  hostname:
    type: string

resources:
  NestedServer:
    type: OS::Nova::Server
    properties:
      name: {get_param: hostname}
      image: {get_param: image}
      key_name: {get_param: key_name}
      flavor: {get_param: flavor}

outputs:
  ip:
    value: {get_attr: [NestedServer, networks, private, 0]}
  OS::stack_id:
    value: {get_resource: NestedServer}
